# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4-browsers
        environment:
          CHROME_BIN: google-chrome

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "functions/package.json" }}
          paths:
            - node_modules
            - functions/node_modules

      - run: npm rebuild node-sass

      - run: yarn test:ci

      - deploy:
          environment:
            NODE_ENV: production
          name: Deploy If Master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              (cd functions && yarn install)

              if npm run build ; then
                ./node_modules/.bin/firebase use firebase-kitchen-kalendar --token "${FIREBASE_CI_TOKEN_PROD}"
                ./node_modules/.bin/firebase deploy --token "${FIREBASE_CI_TOKEN_PROD}"
              else
                exit 1
              fi
            fi
